#pragma once

// The command catalog as it stood before the dynamic-registry migration began
// (doc/spec-command-registry.md).  DATA, not a declaration: nothing is derived
// from it and no production code reads it.  It exists so a migration commit
// cannot silently lose a command, rename one, smuggle one in, or alter a fact
// that governs behaviour or authority while every other check still passes.
//
// Each row is a command's BEHAVIOURAL tuple: id, effect, the shape of its
// arguments, required capabilities, and the two Lua axes.
//
// The argument shape is here because it decides what crosses the wire, and
// because omitting it let the first migrated component change five commands
// from taking a payload to taking none with nothing failing.  Label and summary
// are still excluded: they are cosmetic, a move is a natural moment to improve
// them, and doc/commands.md shows any change in the same diff.
//
// Deleted with the static table at D5.

#include <string_view>
#include <vector>

namespace ssg::frozen {

struct FrozenCommand {
    std::string_view id;
    bool mutates;
    // As the command reference names it, so a change is legible in a diff.
    std::string_view argument;
    std::vector<std::string_view> requiredCapabilities;
    bool luaApi;
    bool initScript;
};

inline std::vector<FrozenCommand> preMigrationCatalog() {
    return {
        {"text.insert", true, "text", {}, true, false},
        {"text.newline", true, "text", {}, true, false},
        {"text.delete_backward", true, "text", {}, true, false},
        {"text.delete_forward", true, "text", {}, true, false},
        {"text.delete_word_backward", true, "text", {}, true, false},
        {"text.delete_word_forward", true, "text", {}, true, false},
        {"cursor.set_position", true, "selection", {}, true, false},
        {"cursor.left", true, "selection", {}, true, false},
        {"cursor.right", true, "selection", {}, true, false},
        {"cursor.word_left", true, "selection", {}, true, false},
        {"cursor.word_right", true, "selection", {}, true, false},
        {"cursor.line_up", true, "selection", {}, true, false},
        {"cursor.line_down", true, "selection", {}, true, false},
        {"cursor.line_start", true, "selection", {}, true, false},
        {"cursor.line_end", true, "selection", {}, true, false},
        {"cursor.page_up", true, "selection", {}, true, false},
        {"cursor.page_down", true, "selection", {}, true, false},
        {"cursor.document_start", true, "selection", {}, true, false},
        {"cursor.document_end", true, "selection", {}, true, false},
        {"select.set_range", true, "selection", {}, true, false},
        {"select.add_range", true, "selection", {}, true, false},
        {"select.left", true, "selection", {}, true, false},
        {"select.right", true, "selection", {}, true, false},
        {"select.word_left", true, "selection", {}, true, false},
        {"select.word_right", true, "selection", {}, true, false},
        {"select.line_up", true, "selection", {}, true, false},
        {"select.line_down", true, "selection", {}, true, false},
        {"select.line_start", true, "selection", {}, true, false},
        {"select.line_end", true, "selection", {}, true, false},
        {"select.page_up", true, "selection", {}, true, false},
        {"select.page_down", true, "selection", {}, true, false},
        {"select.document_start", true, "selection", {}, true, false},
        {"select.document_end", true, "selection", {}, true, false},
        {"select.all", true, "selection", {}, true, false},
        {"select.add_next_occurrence", true, "selection", {}, true, false},
        {"select.add_cursor_up", true, "selection", {}, true, false},
        {"select.add_cursor_down", true, "selection", {}, true, false},
        {"select.split_into_lines", true, "selection", {}, true, false},
        {"select.to_matching_bracket", true, "selection", {}, true, false},
        {"edit.undo", true, "none", {}, true, false},
        {"edit.redo", true, "none", {}, true, false},
        {"edit.indent", true, "none", {}, true, false},
        {"edit.outdent", true, "none", {}, true, false},
        {"edit.duplicate_line", true, "none", {}, true, false},
        {"edit.move_line_up", true, "none", {}, true, false},
        {"edit.move_line_down", true, "none", {}, true, false},
        {"edit.delete_line", true, "none", {}, true, false},
        {"edit.join_lines", true, "none", {}, true, false},
        {"edit.uppercase", true, "none", {}, true, false},
        {"edit.lowercase", true, "none", {}, true, false},
        {"edit.swap_case", true, "none", {}, true, false},
        {"edit.sort_lines", true, "none", {}, true, false},
        {"edit.transpose", true, "none", {}, true, false},
        {"edit.toggle_comment", true, "none", {}, true, false},
        {"clipboard.copy", true, "none", {}, true, false},
        {"clipboard.cut", true, "none", {}, true, false},
        {"clipboard.paste", true, "none", {}, true, false},
        {"view.toggle_word_wrap", true, "none", {}, true, false},
        {"view.scroll_lines", true, "scroll lines", {}, true, false},
        {"view.scroll_pages", true, "scroll pages", {}, true, false},
        {"view.scroll_to_fraction", true, "scroll fraction", {}, true, false},
        {"view.reveal_caret", true, "selection", {}, true, false},
        {"view.center_caret", true, "selection", {}, true, false},
        {"palette.open", true, "none", {}, true, false},
        {"file_finder.open", true, "none", {}, true, false},
        {"file_finder.toggle_gitignore", true, "none", {}, true, false},
        {"palette.close", true, "none", {}, true, false},
        {"palette.next", true, "none", {}, true, false},
        {"palette.previous", true, "none", {}, true, false},
        {"palette.execute", true, "palette selection", {}, true, false},
        {"goto.file", true, "none", {}, true, false},
        {"goto.line", true, "none", {}, true, false},
        {"goto.symbol", true, "none", {}, true, false},
        {"goto.definition", true, "none", {}, true, false},
        {"goto.reference", true, "none", {}, true, false},
        {"goto.matching_bracket", true, "selection", {}, true, false},
        {"goto.back", true, "none", {}, true, false},
        {"goto.forward", true, "none", {}, true, false},
        {"find.open", true, "none", {}, true, false},
        {"find.close", true, "none", {}, true, false},
        {"find.next", true, "none", {}, true, false},
        {"find.previous", true, "none", {}, true, false},
        {"find.update_query", true, "query", {}, true, false},
        {"find.toggle_case", true, "none", {}, true, false},
        {"find.toggle_whole_word", true, "none", {}, true, false},
        {"find.toggle_regex", true, "none", {}, true, false},
        {"find.toggle_selection", true, "none", {}, true, false},
        {"replace.open", true, "none", {}, true, false},
        {"replace.update_replacement", true, "query", {}, true, false},
        {"replace.current", true, "none", {}, true, false},
        {"replace.all", true, "none", {}, true, false},
        {"replace.workspace_preview", true, "workspace replace", {}, true, false},
        {"replace.workspace_apply", true, "workspace apply", {}, true, false},
        {"search.workspace", true, "none", {}, true, false},
        {"search.results_next", true, "none", {}, true, false},
        {"search.results_previous", true, "none", {}, true, false},
        {"completion.open", true, "none", {}, true, false},
        {"completion.next", true, "none", {}, true, false},
        {"completion.previous", true, "none", {}, true, false},
        {"completion.accept", true, "none", {}, true, false},
        {"completion.dismiss", true, "none", {}, true, false},
        {"hover.show", true, "none", {}, true, false},
        {"hover.dismiss", true, "none", {}, true, false},
        {"rename.symbol", true, "none", {}, true, false},
        {"pane.split_horizontal", true, "none", {}, true, false},
        {"pane.split_vertical", true, "none", {}, true, false},
        {"pane.close", true, "none", {}, true, false},
        {"pane.next", true, "none", {}, true, false},
        {"pane.previous", true, "none", {}, true, false},
        {"pane.focus_left", true, "none", {}, true, false},
        {"pane.focus_right", true, "none", {}, true, false},
        {"pane.focus_up", true, "none", {}, true, false},
        {"pane.focus_down", true, "none", {}, true, false},
        {"panel.toggle", true, "none", {}, true, false},
        {"panel.focus", true, "none", {}, true, false},
        {"panel.show_files", true, "none", {}, true, false},
        {"panel.show_git_status", true, "none", {}, true, false},
        {"panel.next_provider", true, "none", {}, true, false},
        {"panel.previous_provider", true, "none", {}, true, false},
        {"tree.toggle_expanded", true, "none", {}, true, false},
        {"tree.invoke_node_command", true, "none", {}, true, false},
        {"tree.select", true, "tree node", {}, true, false},
        {"tree.select_next", true, "none", {}, true, false},
        {"tree.select_previous", true, "none", {}, true, false},
        {"tree.activate", true, "none", {}, true, false},
        {"tree.scroll", true, "scroll lines", {}, true, false},
        {"tree.scroll_to_fraction", true, "scroll fraction", {}, true, false},
        {"view.toggle_distraction_free", true, "none", {}, true, false},
        {"prompt.submit", true, "none", {}, true, false},
        {"prompt.cancel", true, "none", {}, true, false},
        {"prompt.next", true, "none", {}, true, false},
        {"prompt.previous", true, "none", {}, true, false},
        {"prompt.update_value", true, "prompt value", {}, true, false},
        {"status.next", true, "none", {}, true, false},
        {"status.previous", true, "none", {}, true, false},
        {"status.dismiss", true, "none", {}, true, false},
        {"status.invoke_action", true, "none", {}, true, false},
        {"workspace.open_directory", true, "none", {}, true, false},
        {"file.new", true, "none", {}, true, false},
        {"file.open", true, "none", {}, true, false},
        {"file.open_recent", true, "none", {}, true, false},
        {"file.open_dropped_content", true, "dropped content", {"local_file_drop"}, false, false},
        {"file.save", true, "none", {}, true, false},
        {"file.save_all", true, "none", {}, true, false},
        {"file.save_as", true, "none", {}, true, false},
        {"file.reload", true, "none", {}, true, false},
        {"file.rename", true, "none", {}, true, false},
        {"file.delete", true, "none", {}, true, false},
        {"file.new_directory", true, "none", {}, true, false},
        {"file.reopen_with_encoding", true, "encoding", {}, true, false},
        {"file.set_encoding", true, "encoding", {}, true, false},
        {"file.set_line_ending", true, "line ending", {}, true, false},
        {"file.set_final_newline", true, "final newline", {}, true, false},
        {"tab.close", true, "none", {}, true, false},
        {"tab.close_others", true, "none", {}, true, false},
        {"tab.close_all", true, "none", {}, true, false},
        {"tab.reopen_closed", true, "none", {}, true, false},
        {"tab.next", true, "none", {}, true, false},
        {"tab.previous", true, "none", {}, true, false},
        {"tab.activate", true, "none", {}, true, false},
        {"tab.move_left", true, "none", {}, true, false},
        {"tab.move_right", true, "none", {}, true, false},
        {"external.reload", true, "none", {}, true, false},
        {"external.keep_buffer", true, "none", {}, true, false},
        {"external.open_diff", true, "none", {}, true, false},
        {"settings.open", true, "none", {}, true, false},
        {"settings.set", true, "setting", {}, true, false},
        {"settings.reset", true, "setting key", {}, true, false},
        {"settings.reset_scope", true, "setting scope", {}, true, false},
        {"settings.export_workspace", true, "none", {}, true, false},
        {"settings.import_workspace", true, "none", {}, true, false},
        {"theme.define", true, "none", {}, true, true},
        {"theme.background", true, "none", {}, true, true},
        {"style.define", true, "none", {}, true, true},
        {"keymap.bind", true, "none", {}, true, true},
        {"keymap.unbind", true, "none", {}, true, true},
        {"follow_edits.resume", true, "none", {}, true, false},
        {"follow_edits.pause", true, "none", {}, true, false},
        {"follow_edits.toggle", true, "none", {}, true, false},
        {"diff.next_hunk", true, "none", {}, true, false},
        {"diff.previous_hunk", true, "none", {}, true, false},
        {"diff.open_file", true, "none", {}, true, false},
    };
}

}  // namespace ssg::frozen
