#pragma once

// The command catalog as it stood before the dynamic-registry
// migration began (doc/spec-command-registry.md).  DATA, not a
// declaration: nothing is derived from it and no production code
// reads it.  It exists so a migration commit cannot silently lose a
// command, rename one, smuggle one in, or alter a fact that governs
// behaviour or authority while every other check still passes.
//
// Each row is a command's BEHAVIOURAL tuple: id, effect, required
// capabilities, and the two Lua axes.  Label and summary are
// excluded deliberately -- they are cosmetic, a move is a natural
// moment to improve them, and doc/commands.md shows any change in
// the same diff.
//
// Generated once by tools/freeze_catalog.cpp.  Deleted at D5.

#include <string_view>
#include <vector>

namespace ssg::frozen {

struct FrozenCommand {
    std::string_view id;
    bool mutates;
    std::vector<std::string_view> requiredCapabilities;
    bool luaApi;
    bool initScript;
};

inline std::vector<FrozenCommand> preMigrationCatalog() {
    return {
        {"text.insert", true, {}, true, false},
        {"text.newline", true, {}, true, false},
        {"text.delete_backward", true, {}, true, false},
        {"text.delete_forward", true, {}, true, false},
        {"text.delete_word_backward", true, {}, true, false},
        {"text.delete_word_forward", true, {}, true, false},
        {"cursor.set_position", true, {}, true, false},
        {"cursor.left", true, {}, true, false},
        {"cursor.right", true, {}, true, false},
        {"cursor.word_left", true, {}, true, false},
        {"cursor.word_right", true, {}, true, false},
        {"cursor.line_up", true, {}, true, false},
        {"cursor.line_down", true, {}, true, false},
        {"cursor.line_start", true, {}, true, false},
        {"cursor.line_end", true, {}, true, false},
        {"cursor.page_up", true, {}, true, false},
        {"cursor.page_down", true, {}, true, false},
        {"cursor.document_start", true, {}, true, false},
        {"cursor.document_end", true, {}, true, false},
        {"select.set_range", true, {}, true, false},
        {"select.add_range", true, {}, true, false},
        {"select.left", true, {}, true, false},
        {"select.right", true, {}, true, false},
        {"select.word_left", true, {}, true, false},
        {"select.word_right", true, {}, true, false},
        {"select.line_up", true, {}, true, false},
        {"select.line_down", true, {}, true, false},
        {"select.line_start", true, {}, true, false},
        {"select.line_end", true, {}, true, false},
        {"select.page_up", true, {}, true, false},
        {"select.page_down", true, {}, true, false},
        {"select.document_start", true, {}, true, false},
        {"select.document_end", true, {}, true, false},
        {"select.all", true, {}, true, false},
        {"select.add_next_occurrence", true, {}, true, false},
        {"select.add_cursor_up", true, {}, true, false},
        {"select.add_cursor_down", true, {}, true, false},
        {"select.split_into_lines", true, {}, true, false},
        {"select.to_matching_bracket", true, {}, true, false},
        {"edit.undo", true, {}, true, false},
        {"edit.redo", true, {}, true, false},
        {"edit.indent", true, {}, true, false},
        {"edit.outdent", true, {}, true, false},
        {"edit.duplicate_line", true, {}, true, false},
        {"edit.move_line_up", true, {}, true, false},
        {"edit.move_line_down", true, {}, true, false},
        {"edit.delete_line", true, {}, true, false},
        {"edit.join_lines", true, {}, true, false},
        {"edit.uppercase", true, {}, true, false},
        {"edit.lowercase", true, {}, true, false},
        {"edit.swap_case", true, {}, true, false},
        {"edit.sort_lines", true, {}, true, false},
        {"edit.transpose", true, {}, true, false},
        {"edit.toggle_comment", true, {}, true, false},
        {"clipboard.copy", true, {}, true, false},
        {"clipboard.cut", true, {}, true, false},
        {"clipboard.paste", true, {}, true, false},
        {"view.toggle_word_wrap", true, {}, true, false},
        {"view.scroll_lines", true, {}, true, false},
        {"view.scroll_pages", true, {}, true, false},
        {"view.scroll_to_fraction", true, {}, true, false},
        {"view.reveal_caret", true, {}, true, false},
        {"view.center_caret", true, {}, true, false},
        {"palette.open", true, {}, true, false},
        {"file_finder.open", true, {}, true, false},
        {"file_finder.toggle_gitignore", true, {}, true, false},
        {"palette.close", true, {}, true, false},
        {"palette.next", true, {}, true, false},
        {"palette.previous", true, {}, true, false},
        {"palette.execute", true, {}, true, false},
        {"goto.file", true, {}, true, false},
        {"goto.line", true, {}, true, false},
        {"goto.symbol", true, {}, true, false},
        {"goto.definition", true, {}, true, false},
        {"goto.reference", true, {}, true, false},
        {"goto.matching_bracket", true, {}, true, false},
        {"goto.back", true, {}, true, false},
        {"goto.forward", true, {}, true, false},
        {"find.open", true, {}, true, false},
        {"find.close", true, {}, true, false},
        {"find.next", true, {}, true, false},
        {"find.previous", true, {}, true, false},
        {"find.update_query", true, {}, true, false},
        {"find.toggle_case", true, {}, true, false},
        {"find.toggle_whole_word", true, {}, true, false},
        {"find.toggle_regex", true, {}, true, false},
        {"find.toggle_selection", true, {}, true, false},
        {"replace.open", true, {}, true, false},
        {"replace.update_replacement", true, {}, true, false},
        {"replace.current", true, {}, true, false},
        {"replace.all", true, {}, true, false},
        {"replace.workspace_preview", true, {}, true, false},
        {"replace.workspace_apply", true, {}, true, false},
        {"search.workspace", true, {}, true, false},
        {"search.results_next", true, {}, true, false},
        {"search.results_previous", true, {}, true, false},
        {"completion.open", true, {}, true, false},
        {"completion.next", true, {}, true, false},
        {"completion.previous", true, {}, true, false},
        {"completion.accept", true, {}, true, false},
        {"completion.dismiss", true, {}, true, false},
        {"hover.show", true, {}, true, false},
        {"hover.dismiss", true, {}, true, false},
        {"rename.symbol", true, {}, true, false},
        {"pane.split_horizontal", true, {}, true, false},
        {"pane.split_vertical", true, {}, true, false},
        {"pane.close", true, {}, true, false},
        {"pane.next", true, {}, true, false},
        {"pane.previous", true, {}, true, false},
        {"pane.focus_left", true, {}, true, false},
        {"pane.focus_right", true, {}, true, false},
        {"pane.focus_up", true, {}, true, false},
        {"pane.focus_down", true, {}, true, false},
        {"panel.toggle", true, {}, true, false},
        {"panel.focus", true, {}, true, false},
        {"panel.show_files", true, {}, true, false},
        {"panel.show_git_status", true, {}, true, false},
        {"panel.next_provider", true, {}, true, false},
        {"panel.previous_provider", true, {}, true, false},
        {"tree.toggle_expanded", true, {}, true, false},
        {"tree.invoke_node_command", true, {}, true, false},
        {"tree.select", true, {}, true, false},
        {"tree.select_next", true, {}, true, false},
        {"tree.select_previous", true, {}, true, false},
        {"tree.activate", true, {}, true, false},
        {"tree.scroll", true, {}, true, false},
        {"tree.scroll_to_fraction", true, {}, true, false},
        {"view.toggle_distraction_free", true, {}, true, false},
        {"prompt.submit", true, {}, true, false},
        {"prompt.cancel", true, {}, true, false},
        {"prompt.next", true, {}, true, false},
        {"prompt.previous", true, {}, true, false},
        {"prompt.update_value", true, {}, true, false},
        {"status.next", true, {}, true, false},
        {"status.previous", true, {}, true, false},
        {"status.dismiss", true, {}, true, false},
        {"status.invoke_action", true, {}, true, false},
        {"workspace.open_directory", true, {}, true, false},
        {"file.new", true, {}, true, false},
        {"file.open", true, {}, true, false},
        {"file.open_recent", true, {}, true, false},
        {"file.open_dropped_content", true, {"local_file_drop"}, false, false},
        {"file.save", true, {}, true, false},
        {"file.save_all", true, {}, true, false},
        {"file.save_as", true, {}, true, false},
        {"file.reload", true, {}, true, false},
        {"file.rename", true, {}, true, false},
        {"file.delete", true, {}, true, false},
        {"file.new_directory", true, {}, true, false},
        {"file.reopen_with_encoding", true, {}, true, false},
        {"file.set_encoding", true, {}, true, false},
        {"file.set_line_ending", true, {}, true, false},
        {"file.set_final_newline", true, {}, true, false},
        {"tab.close", true, {}, true, false},
        {"tab.close_others", true, {}, true, false},
        {"tab.close_all", true, {}, true, false},
        {"tab.reopen_closed", true, {}, true, false},
        {"tab.next", true, {}, true, false},
        {"tab.previous", true, {}, true, false},
        {"tab.activate", true, {}, true, false},
        {"tab.move_left", true, {}, true, false},
        {"tab.move_right", true, {}, true, false},
        {"external.reload", true, {}, true, false},
        {"external.keep_buffer", true, {}, true, false},
        {"external.open_diff", true, {}, true, false},
        {"settings.open", true, {}, true, false},
        {"settings.set", true, {}, true, false},
        {"settings.reset", true, {}, true, false},
        {"settings.reset_scope", true, {}, true, false},
        {"settings.export_workspace", true, {}, true, false},
        {"settings.import_workspace", true, {}, true, false},
        {"theme.define", true, {}, true, true},
        {"theme.background", true, {}, true, true},
        {"style.define", true, {}, true, true},
        {"keymap.bind", true, {}, true, true},
        {"keymap.unbind", true, {}, true, true},
        {"follow_edits.resume", true, {}, true, false},
        {"follow_edits.pause", true, {}, true, false},
        {"follow_edits.toggle", true, {}, true, false},
        {"diff.next_hunk", true, {}, true, false},
        {"diff.previous_hunk", true, {}, true, false},
        {"diff.open_file", true, {}, true, false},
    };
}

}  // namespace ssg::frozen
