#!/usr/bin/env python3
"""Generate k_extpic[] C++ array from emoji-data.txt (Unicode 15.0.0).

Usage:
    python3 tools/gen_extpic_table.py data/unicode/emoji-data.txt

Output is written to stdout.  Adjacent or overlapping Extended_Pictographic
ranges are merged so the result is a minimal sorted non-overlapping URange array
suitable for embedding directly in src/grapheme_layout.cpp.
"""

import re
import sys


def parse(path):
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            raw = line.split("#")[0].strip()
            if not raw or "Extended_Pictographic" not in raw:
                continue
            m = re.match(
                r"([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*Extended_Pictographic",
                raw,
            )
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            ranges.append([lo, hi])
    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    return merged


def emit(merged):
    total_cps = sum(hi - lo + 1 for lo, hi in merged)
    print("// Generated by tools/gen_extpic_table.py from")
    print("// data/unicode/emoji-data.txt (Unicode 15.0.0)")
    print(f"// {len(merged)} ranges, {total_cps} code points.")
    print("static constexpr URange k_extpic[] = {")
    for lo, hi in merged:
        print(f"    {{0x{lo:04X}, 0x{hi:04X}}},")
    print("};")
    print("static constexpr int k_extpic_n =")
    print("    static_cast<int>(sizeof(k_extpic) / sizeof(k_extpic[0]));")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <emoji-data.txt>", file=sys.stderr)
        sys.exit(1)
    emit(parse(sys.argv[1]))
