#!/usr/bin/env python3
"""Generate k_gcb[] C++ array from GraphemeBreakProperty.txt (Unicode 15.0.0).

Usage:
    python3 tools/gen_gcb_table.py data/unicode/GraphemeBreakProperty.txt

Output is written to stdout.  LV and LVT syllable entries are excluded
(they are computed by (cp - 0xAC00) % 28 in gcb_prop_of()).

The output is a sorted, non-overlapping array of GcbRange entries suitable
for embedding directly in src/grapheme_layout.cpp.
"""

import re
import sys

PROP_MAP = {
    "CR":                "GcbProp::CR",
    "LF":                "GcbProp::LF",
    "Control":           "GcbProp::Control",
    "Extend":            "GcbProp::Extend",
    "ZWJ":               "GcbProp::ZWJ",
    "SpacingMark":       "GcbProp::SpacingMark",
    "L":                 "GcbProp::L",
    "V":                 "GcbProp::V",
    "T":                 "GcbProp::T",
    "LV":                None,   # computed, excluded
    "LVT":               None,   # computed, excluded
    "Prepend":           "GcbProp::Prepend",
    "Regional_Indicator":"GcbProp::RI",
}

def parse(path):
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#")[0].strip()
            if not line:
                continue
            m = re.match(r"([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*(\S+)", line)
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            prop = m.group(3)
            cpp = PROP_MAP.get(prop)
            if cpp is None:
                continue  # LV, LVT, or unknown property
            ranges.append((lo, hi, cpp, prop))
    ranges.sort(key=lambda r: r[0])
    return ranges

def emit(ranges):
    print("// Generated by tools/gen_gcb_table.py from")
    print("// data/unicode/GraphemeBreakProperty.txt (Unicode 15.0.0)")
    print("// LV and LVT entries excluded (computed in gcb_prop_of).")
    print(f"static constexpr GcbRange k_gcb[] = {{")
    for lo, hi, cpp, prop in ranges:
        if lo == hi:
            print(f"    {{0x{lo:04X}, 0x{hi:04X}, {cpp}}},  // {prop}")
        else:
            print(f"    {{0x{lo:04X}, 0x{hi:04X}, {cpp}}},  // {prop}")
    print("};")
    print(f"static constexpr int k_gcb_n =")
    print(f"    static_cast<int>(sizeof(k_gcb) / sizeof(k_gcb[0]));")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <GraphemeBreakProperty.txt>", file=sys.stderr)
        sys.exit(1)
    emit(parse(sys.argv[1]))
