#!/usr/bin/env python3
"""Generate k_emoji_pres[] and k_emoji[] C++ arrays from emoji-data.txt (Unicode 15.0.0).

Usage:
    python3 tools/gen_emoji_props_table.py data/unicode/emoji-data.txt

Output is written to stdout:
  k_emoji_pres[] — Emoji_Presentation property (characters that default to
                   emoji presentation and occupy 2 terminal columns).
  k_emoji[]      — Emoji property (characters eligible for VS-16 emoji
                   presentation sequences; used to detect Emoji + U+FE0F → 2).

Both arrays are minimal, sorted, non-overlapping URange arrays.
"""

import re
import sys


def parse_prop(path, prop):
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            raw = line.split("#")[0].strip()
            if not raw or f"; {prop}" not in raw:
                continue
            m = re.match(
                r"([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*" + prop + r"\b",
                raw,
            )
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            ranges.append([lo, hi])
    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], hi)
        else:
            merged.append([lo, hi])
    return merged


def emit_array(name, size_name, merged, comment):
    total_cps = sum(hi - lo + 1 for lo, hi in merged)
    print(f"// {comment}")
    print(f"// {len(merged)} ranges, {total_cps} code points.")
    print(f"static constexpr URange {name}[] = {{")
    for lo, hi in merged:
        print(f"    {{0x{lo:04X}, 0x{hi:04X}}},")
    print("};")
    print(f"static constexpr int {size_name} =")
    print(f"    static_cast<int>(sizeof({name}) / sizeof({name}[0]));")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <emoji-data.txt>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    pres = parse_prop(path, "Emoji_Presentation")
    emoji = parse_prop(path, "Emoji")

    print("// Generated by tools/gen_emoji_props_table.py from")
    print("// data/unicode/emoji-data.txt (Unicode 15.0.0)")
    print()
    emit_array(
        "k_emoji_pres",
        "k_emoji_pres_n",
        pres,
        "Emoji_Presentation: default emoji-presentation characters (2 terminal columns).",
    )
    print()
    emit_array(
        "k_emoji",
        "k_emoji_n",
        emoji,
        "Emoji: all characters with the Emoji property.",
        )
