#!/usr/bin/env python3
"""Generate k_wide[] C++ array from EastAsianWidth.txt (Unicode 15.0.0).

Usage:
    python3 tools/gen_eaw_table.py data/unicode/east_asian_width.txt

Output is written to stdout.  Only EAW=W (Wide) and EAW=F (Fullwidth) entries
are emitted.  Adjacent ranges with the same effective property are merged into
a minimal sorted non-overlapping URange array suitable for embedding directly
in src/layout.cpp.
"""

import re
import sys


def parse(path):
    ranges = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            raw = line.split("#")[0].strip()
            if not raw:
                continue
            m = re.match(
                r"([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([WF])\b",
                raw,
            )
            if not m:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            ranges.append([lo, hi])
    ranges.sort()
    merged = []
    for lo, hi in ranges:
        if merged and lo == merged[-1][1] + 1:
            merged[-1][1] = hi
        else:
            merged.append([lo, hi])
    return merged


def emit(merged):
    total_cps = sum(hi - lo + 1 for lo, hi in merged)
    print("// Generated by tools/gen_eaw_table.py from")
    print("// data/unicode/east_asian_width.txt (Unicode 15.0.0)")
    print(f"// EAW=W or EAW=F: {len(merged)} ranges, {total_cps} code points.")
    print("static constexpr URange k_wide[] = {")
    for lo, hi in merged:
        print(f"    {{0x{lo:04X}, 0x{hi:04X}}},")
    print("};")
    print("static constexpr int k_wide_n =")
    print("    static_cast<int>(sizeof(k_wide) / sizeof(k_wide[0]));")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <EastAsianWidth.txt>", file=sys.stderr)
        sys.exit(1)
    emit(parse(sys.argv[1]))
