#include "ssg/Commands.h"

#include <algorithm>
#include <array>

namespace ssg {
namespace {

constexpr std::array<std::string_view, 1> kfile_open_dropped_contentCapabilities{"local_file_drop"};

// THE command catalog.  One row per command, hand-authored and reviewed as data.
//
// Adding a command means adding a row here and binding its handler.  Nothing
// else declares a command id: the assembled registry, the protocol argument
// codecs, palette labels, Lua host grants and the generated command reference
// are all projections of this table (doc/spec-commands.md).
//
// Columns: id, owner, label ("" = humanise the id), summary, effect, argument
// shape, surfaces {luaApi, initScript}, required capabilities.
constexpr std::array<CommandSpec, 182> kCommands{{
    {"text.insert", "text-input-commands", "", "Insert",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"text.newline", "text-input-commands", "", "Newline",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"text.delete_backward", "text-input-commands", "", "Delete Backward",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"text.delete_forward", "text-input-commands", "", "Delete Forward",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"text.delete_word_backward", "text-input-commands", "", "Delete Word Backward",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"text.delete_word_forward", "text-input-commands", "", "Delete Word Forward",
     CommandEffect::Mutation, ArgumentKind::TextInput, {true, false},
     {}},
    {"cursor.set_position", "selection-navigation", "", "Set Position",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.left", "selection-navigation", "", "Left",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.right", "selection-navigation", "", "Right",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.word_left", "selection-navigation", "", "Word Left",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.word_right", "selection-navigation", "", "Word Right",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.line_up", "selection-navigation", "", "Line Up",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.line_down", "selection-navigation", "", "Line Down",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.line_start", "selection-navigation", "", "Line Start",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.line_end", "selection-navigation", "", "Line End",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.page_up", "selection-navigation", "", "Page Up",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.page_down", "selection-navigation", "", "Page Down",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.document_start", "selection-navigation", "", "Document Start",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"cursor.document_end", "selection-navigation", "", "Document End",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.set_range", "selection-navigation", "", "Set Range",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.add_range", "selection-navigation", "", "Add Range",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.left", "selection-navigation", "", "Left",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.right", "selection-navigation", "", "Right",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.word_left", "selection-navigation", "", "Word Left",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.word_right", "selection-navigation", "", "Word Right",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.line_up", "selection-navigation", "", "Line Up",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.line_down", "selection-navigation", "", "Line Down",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.line_start", "selection-navigation", "", "Line Start",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.line_end", "selection-navigation", "", "Line End",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.page_up", "selection-navigation", "", "Page Up",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.page_down", "selection-navigation", "", "Page Down",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.document_start", "selection-navigation", "", "Document Start",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.document_end", "selection-navigation", "", "Document End",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.all", "selection-navigation", "", "All",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.add_next_occurrence", "selection-navigation", "", "Add Next Occurrence",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.add_cursor_up", "selection-navigation", "", "Add Cursor Up",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.add_cursor_down", "selection-navigation", "", "Add Cursor Down",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.split_into_lines", "selection-navigation", "", "Split Into Lines",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"select.to_matching_bracket", "selection-navigation", "", "To Matching Bracket",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"edit.undo", "undo-redo-history", "Undo", "Undo",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.redo", "undo-redo-history", "Redo", "Redo",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.indent", "edit-command-suite", "Indent", "Indent",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.outdent", "edit-command-suite", "Outdent", "Outdent",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.duplicate_line", "edit-command-suite", "", "Duplicate Line",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.move_line_up", "edit-command-suite", "", "Move Line Up",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.move_line_down", "edit-command-suite", "", "Move Line Down",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.delete_line", "edit-command-suite", "", "Delete Line",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.join_lines", "edit-command-suite", "", "Join Lines",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.uppercase", "edit-command-suite", "", "Uppercase",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.lowercase", "edit-command-suite", "", "Lowercase",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.swap_case", "edit-command-suite", "", "Swap Case",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.sort_lines", "edit-command-suite", "", "Sort Lines",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.transpose", "edit-command-suite", "", "Transpose",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"edit.toggle_comment", "edit-command-suite", "Toggle Comment", "Toggle Comment",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"clipboard.copy", "clipboard-register", "Copy", "Copy",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"clipboard.cut", "clipboard-register", "Cut", "Cut",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"clipboard.paste", "clipboard-register", "Paste", "Paste",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"view.toggle_word_wrap", "viewport-wrap-scrollbar", "Toggle Word Wrap", "Toggle Word Wrap",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"view.scroll_lines", "viewport-wrap-scrollbar", "", "Scroll Lines",
     CommandEffect::Mutation, ArgumentKind::ScrollLines, {true, false},
     {}},
    {"view.scroll_pages", "viewport-wrap-scrollbar", "", "Scroll Pages",
     CommandEffect::Mutation, ArgumentKind::ScrollPages, {true, false},
     {}},
    {"view.scroll_to_fraction", "viewport-wrap-scrollbar", "", "Scroll To Fraction",
     CommandEffect::Mutation, ArgumentKind::ScrollFraction, {true, false},
     {}},
    {"view.reveal_caret", "selection-navigation", "", "Reveal Caret",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"view.center_caret", "selection-navigation", "", "Center Caret",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"palette.open", "search-palette", "Command Palette", "Command Palette",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file_finder.open", "search-palette", "", "Open",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file_finder.toggle_gitignore", "search-palette", "", "Toggle Gitignore",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"palette.close", "search-palette", "", "Close",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"palette.next", "search-palette", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"palette.previous", "search-palette", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"palette.execute", "search-palette", "", "Execute",
     CommandEffect::Mutation, ArgumentKind::PaletteExecute, {true, false},
     {}},
    {"goto.file", "search-palette", "Go to File", "Go to File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.line", "search-palette", "Go to Line", "Go to Line",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.symbol", "search-palette", "Go to Symbol", "Go to Symbol",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.definition", "lsp-language-features", "Go to Definition", "Go to Definition",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.reference", "lsp-language-features", "", "Reference",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.matching_bracket", "selection-navigation", "", "Matching Bracket",
     CommandEffect::Mutation, ArgumentKind::SelectionCommand, {true, false},
     {}},
    {"goto.back", "search-palette", "", "Back",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"goto.forward", "search-palette", "", "Forward",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.open", "find-replace", "Find", "Find",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.close", "find-replace", "", "Close",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.next", "find-replace", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.previous", "find-replace", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.update_query", "find-replace", "", "Update Query",
     CommandEffect::Mutation, ArgumentKind::FindQuery, {true, false},
     {}},
    {"find.toggle_case", "find-replace", "", "Toggle Case",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.toggle_whole_word", "find-replace", "", "Toggle Whole Word",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.toggle_regex", "find-replace", "", "Toggle Regex",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"find.toggle_selection", "find-replace", "", "Toggle Selection",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"replace.open", "find-replace", "Replace", "Replace",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"replace.update_replacement", "find-replace", "", "Update Replacement",
     CommandEffect::Mutation, ArgumentKind::FindQuery, {true, false},
     {}},
    {"replace.current", "find-replace", "", "Current",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"replace.all", "find-replace", "", "All",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"replace.workspace_preview", "find-replace", "", "Workspace Preview",
     CommandEffect::Mutation, ArgumentKind::WorkspaceReplace, {true, false},
     {}},
    {"replace.workspace_apply", "find-replace", "", "Workspace Apply",
     CommandEffect::Mutation, ArgumentKind::WorkspaceApply, {true, false},
     {}},
    {"search.workspace", "search-palette", "", "Workspace",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"search.results_next", "search-palette", "", "Results Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"search.results_previous", "search-palette", "", "Results Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"completion.open", "lsp-language-features", "", "Open",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"completion.next", "lsp-language-features", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"completion.previous", "lsp-language-features", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"completion.accept", "lsp-language-features", "", "Accept",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"completion.dismiss", "lsp-language-features", "", "Dismiss",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"hover.show", "lsp-language-features", "", "Show",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"hover.dismiss", "lsp-language-features", "", "Dismiss",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"rename.symbol", "lsp-workspace-edits", "", "Symbol",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.split_horizontal", "shell-layout", "", "Split Horizontal",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.split_vertical", "shell-layout", "", "Split Vertical",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.close", "shell-layout", "", "Close",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.next", "shell-layout", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.previous", "shell-layout", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.focus_left", "shell-layout", "", "Focus Left",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.focus_right", "shell-layout", "", "Focus Right",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.focus_up", "shell-layout", "", "Focus Up",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"pane.focus_down", "shell-layout", "", "Focus Down",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.toggle", "shell-layout", "Toggle Sidebar", "Toggle Sidebar",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.focus", "shell-layout", "Focus Sidebar", "Focus Sidebar",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.show_files", "shell-layout", "Show Files Sidebar", "Show Files Sidebar",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.show_git_status", "shell-layout", "Show Git Sidebar", "Show Git Sidebar",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.next_provider", "shell-layout", "", "Next Provider",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"panel.previous_provider", "shell-layout", "", "Previous Provider",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.toggle_expanded", "tree-providers", "", "Toggle Expanded",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.invoke_node_command", "tree-providers", "", "Invoke Node Command",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.select", "tree-providers", "", "Select",
     CommandEffect::Mutation, ArgumentKind::TreeSelect, {true, false},
     {}},
    {"tree.select_next", "tree-providers", "", "Select Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.select_previous", "tree-providers", "", "Select Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.activate", "tree-providers", "Open Selected", "Open Selected",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tree.scroll", "tree-providers", "", "Scroll",
     CommandEffect::Mutation, ArgumentKind::ScrollLines, {true, false},
     {}},
    {"tree.scroll_to_fraction", "tree-providers", "", "Scroll To Fraction",
     CommandEffect::Mutation, ArgumentKind::ScrollFraction, {true, false},
     {}},
    {"view.toggle_distraction_free", "shell-layout", "", "Toggle Distraction Free",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"prompt.submit", "prompt-status-surface", "Submit Prompt", "Submit Prompt",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"prompt.cancel", "prompt-status-surface", "", "Cancel",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"prompt.next", "prompt-status-surface", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"prompt.previous", "prompt-status-surface", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"prompt.update_value", "prompt-status-surface", "", "Update Value",
     CommandEffect::Mutation, ArgumentKind::PromptValue, {true, false},
     {}},
    {"status.next", "prompt-status-surface", "", "Next",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"status.previous", "prompt-status-surface", "", "Previous",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"status.dismiss", "prompt-status-surface", "", "Dismiss",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"status.invoke_action", "prompt-status-surface", "", "Invoke Action",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"workspace.open_directory", "file-commands", "", "Open Directory",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.new", "file-commands", "New File", "New File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.open", "file-commands", "Open File", "Open File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.open_recent", "file-commands", "", "Open Recent",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.open_dropped_content", "file-commands", "", "Open Dropped Content",
     CommandEffect::Mutation, ArgumentKind::DroppedContent, {false, false},
     kfile_open_dropped_contentCapabilities},
    {"file.save", "file-commands", "Save File", "Save File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.save_all", "file-commands", "Save All Files", "Save All Files",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.save_as", "file-commands", "Save File As", "Save File As",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.reload", "file-commands", "Reload File", "Reload File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.rename", "file-commands", "Rename File", "Rename File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.delete", "file-commands", "Delete File", "Delete File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.new_directory", "file-commands", "", "New Directory",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"file.reopen_with_encoding", "encoding-eol", "", "Reopen With Encoding",
     CommandEffect::Mutation, ArgumentKind::ReopenWithEncoding, {true, false},
     {}},
    {"file.set_encoding", "encoding-eol", "", "Set Encoding",
     CommandEffect::Mutation, ArgumentKind::SetEncoding, {true, false},
     {}},
    {"file.set_line_ending", "encoding-eol", "", "Set Line Ending",
     CommandEffect::Mutation, ArgumentKind::SetLineEnding, {true, false},
     {}},
    {"file.set_final_newline", "encoding-eol", "", "Set Final Newline",
     CommandEffect::Mutation, ArgumentKind::SetFinalNewline, {true, false},
     {}},
    {"tab.close", "tab-management", "Close Tab", "Close Tab",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.close_others", "tab-management", "Close Other Tabs", "Close Other Tabs",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.close_all", "tab-management", "Close All Tabs", "Close All Tabs",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.reopen_closed", "tab-management", "", "Reopen Closed",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.next", "tab-management", "Next Tab", "Next Tab",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.previous", "tab-management", "Previous Tab", "Previous Tab",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.activate", "tab-management", "", "Activate",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.move_left", "tab-management", "", "Move Left",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"tab.move_right", "tab-management", "", "Move Right",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"external.reload", "external-modification-flow", "", "Reload",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"external.keep_buffer", "external-modification-flow", "", "Keep Buffer",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"external.open_diff", "external-modification-flow", "", "Open Diff",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"settings.open", "settings-model", "Open Settings", "Open Settings",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"settings.set", "settings-model", "", "Set",
     CommandEffect::Mutation, ArgumentKind::SettingSet, {true, false},
     {}},
    {"settings.reset", "settings-model", "", "Reset",
     CommandEffect::Mutation, ArgumentKind::SettingReset, {true, false},
     {}},
    {"settings.reset_scope", "settings-model", "", "Reset Scope",
     CommandEffect::Mutation, ArgumentKind::SettingResetScope, {true, false},
     {}},
    {"settings.export_workspace", "settings-model", "", "Export Workspace",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"settings.import_workspace", "settings-model", "", "Import Workspace",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"theme.define", "theme-model", "", "Define",
     CommandEffect::Mutation, ArgumentKind::None, {true, true},
     {}},
    {"theme.background", "theme-model", "", "Background",
     CommandEffect::Mutation, ArgumentKind::None, {true, true},
     {}},
    {"style.define", "style-model", "", "Define",
     CommandEffect::Mutation, ArgumentKind::None, {true, true},
     {}},
    {"keymap.bind", "keymap-model", "", "Bind",
     CommandEffect::Mutation, ArgumentKind::None, {true, true},
     {}},
    {"keymap.unbind", "keymap-model", "", "Unbind",
     CommandEffect::Mutation, ArgumentKind::None, {true, true},
     {}},
    {"follow_edits.resume", "follow-edits", "", "Resume",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"follow_edits.pause", "follow-edits", "", "Pause",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"follow_edits.toggle", "follow-edits", "", "Toggle",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"diff.next_hunk", "diff-model", "", "Next Hunk",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"diff.previous_hunk", "diff-model", "", "Previous Hunk",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
    {"diff.open_file", "diff-model", "", "Open File",
     CommandEffect::Mutation, ArgumentKind::None, {true, false},
     {}},
}};

}  // namespace

std::span<CommandSpec const> commandCatalog() { return kCommands; }

std::vector<CommandSpec const*> commandsOwnedBy(std::string_view owner) {
    std::vector<CommandSpec const*> owned;
    for (auto const& command : kCommands) {
        if (command.owner == owner) owned.push_back(&command);
    }
    return owned;
}

CommandSpec const* findCommand(std::string_view id) {
    auto const found = std::ranges::find(kCommands, id, &CommandSpec::id);
    return found == kCommands.end() ? nullptr : &*found;
}

}  // namespace ssg
