# Generates a C++ translation unit embedding text files as string_views, so the
# binary carries them instead of reading them from the source tree at runtime.
#
# Run at BUILD time (not configure time) via a custom command, so editing an
# embedded file regenerates the TU.
#
# Inputs (via -D):
#   EMBED_SPEC_FILE  file of newline-separated "key=path" pairs.  A file, not a
#                    -D value: a ';'-separated list is truncated at the first
#                    ';' by the command-line parser and a newline-joined string
#                    has its newlines stripped under VERBATIM.  Both failures
#                    are SILENT -- they yield a partial table that compiles.
#   EMBED_OUTPUT output .cpp path
#   EMBED_NAMESPACE  namespace to emit into
#   EMBED_ACCESSOR   accessor function name

# A raw-string delimiter chosen not to appear in query text.  The plain R"(...)"
# form is NOT safe here: tree-sitter highlight queries legitimately contain the
# sequence )" (for example a predicate ending in a quoted string), which would
# terminate the literal early and produce a confusing error in generated code.
set(_delimiter "SSGEMBED")

set(_output "// Generated by cmake/embed_text.cmake. Do not edit.\n")
string(APPEND _output "#include <string_view>\n\n")
string(APPEND _output "namespace ${EMBED_NAMESPACE} {\n\n")

set(_body "")
set(_emitted 0)
if(NOT EXISTS "${EMBED_SPEC_FILE}")
    message(FATAL_ERROR "embed_text: missing spec file: ${EMBED_SPEC_FILE}")
endif()
file(STRINGS "${EMBED_SPEC_FILE}" _entries)
list(LENGTH _entries _requested)
if(_requested EQUAL 0)
    message(FATAL_ERROR "embed_text: ${EMBED_SPEC_FILE} is empty")
endif()
foreach(_entry IN LISTS _entries)
    if(_entry STREQUAL "")
        continue()
    endif()
    string(FIND "${_entry}" "=" _split)
    if(_split EQUAL -1)
        message(FATAL_ERROR "embed_text: malformed entry (want key=path): ${_entry}")
    endif()
    string(SUBSTRING "${_entry}" 0 ${_split} _key)
    math(EXPR _rest "${_split} + 1")
    string(SUBSTRING "${_entry}" ${_rest} -1 _path)

    if(NOT EXISTS "${_path}")
        message(FATAL_ERROR "embed_text: missing source file for '${_key}': ${_path}")
    endif()
    file(READ "${_path}" _text)

    # The delimiter check is the whole reason a fixed delimiter is safe.  Without
    # it, a future grammar containing )SSGEMBED" would silently truncate.
    string(FIND "${_text}" ")${_delimiter}\"" _collision)
    if(NOT _collision EQUAL -1)
        message(FATAL_ERROR
            "embed_text: ${_path} contains the raw-string terminator )${_delimiter}\" "
            "at offset ${_collision}; choose a different delimiter in "
            "cmake/embed_text.cmake")
    endif()

    string(APPEND _body
        "    if (key == \"${_key}\") {\n"
        "        return std::string_view{R\"${_delimiter}(${_text})${_delimiter}\"};\n"
        "    }\n")
    math(EXPR _emitted "${_emitted} + 1")
endforeach()

# A silently short table is the failure this generator is most prone to (an
# argument mangled in transit yields a partial list that still "works" for the
# first grammar).  Refuse to emit one.
if(NOT _emitted EQUAL _requested)
    message(FATAL_ERROR
        "embed_text: emitted ${_emitted} of ${_requested} entries; the spec was "
        "mangled in transit")
endif()

string(APPEND _output
    "// Returns the embedded text for `key`, or an empty view when the key is\n"
    "// unknown.  Callers treat empty as a programming error: every key comes\n"
    "// from a compiled-in table, so a miss means the table and this generated\n"
    "// file disagree.\n")
string(APPEND _output
    "std::string_view ${EMBED_ACCESSOR}(std::string_view key) {\n")
string(APPEND _output "${_body}")
string(APPEND _output "    return {};\n}\n\n")
string(APPEND _output "}  // namespace ${EMBED_NAMESPACE}\n")
file(WRITE "${EMBED_OUTPUT}" "${_output}")
