include_guard(GLOBAL)

function(ssg_declare_layer)
    set(_options)
    set(_oneValue TARGET ROOT)
    set(_multiValue ALLOWS PRIVATE_ROOTS HEADERS)
    cmake_parse_arguments(LAYER
        "${_options}" "${_oneValue}" "${_multiValue}" ${ARGN})

    if(NOT LAYER_TARGET OR NOT TARGET "${LAYER_TARGET}")
        message(FATAL_ERROR "SSG layer violation: declaration has no target")
    endif()
    if(NOT LAYER_ROOT)
        message(FATAL_ERROR
            "SSG layer violation: ${LAYER_TARGET} has no public root")
    endif()

    get_filename_component(_root "${LAYER_ROOT}" ABSOLUTE)
    set_property(TARGET "${LAYER_TARGET}" PROPERTY SSG_LAYER_DECLARED TRUE)
    set_property(TARGET "${LAYER_TARGET}" PROPERTY SSG_LAYER_ROOT "${_root}")
    set_property(TARGET "${LAYER_TARGET}" PROPERTY
        SSG_LAYER_PRIVATE_ROOTS "${LAYER_PRIVATE_ROOTS}")
    set_property(TARGET "${LAYER_TARGET}" PROPERTY
        SSG_LAYER_ALLOWS "${LAYER_ALLOWS}")
    if(NOT LAYER_HEADERS)
        file(GLOB_RECURSE _headerFiles
            RELATIVE "${_root}/ssg"
            "${_root}/ssg/*.h"
            "${_root}/ssg/*.hpp")
        set(LAYER_HEADERS ${_headerFiles})
    endif()
    set_property(TARGET "${LAYER_TARGET}" PROPERTY
        SSG_LAYER_HEADERS "${LAYER_HEADERS}")
    set_property(GLOBAL APPEND PROPERTY SSG_LAYER_TARGETS "${LAYER_TARGET}")

    target_include_directories("${LAYER_TARGET}" PUBLIC "${_root}")
endfunction()

function(ssg_allow_private_roots target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR
            "SSG layer violation: private roots name missing ${target}")
    endif()
    get_target_property(_roots "${target}" SSG_LAYER_PRIVATE_ROOTS)
    if(NOT _roots OR _roots STREQUAL "_roots-NOTFOUND")
        set(_roots)
    endif()
    foreach(_root IN LISTS ARGN)
        get_filename_component(_root "${_root}" ABSOLUTE)
        list(APPEND _roots "${_root}")
    endforeach()
    set_property(TARGET "${target}" PROPERTY SSG_LAYER_PRIVATE_ROOTS "${_roots}")
endfunction()

function(_ssg_layer_closure target output)
    get_target_property(_allows "${target}" SSG_LAYER_ALLOWS)
    if(NOT _allows OR _allows STREQUAL "_allows-NOTFOUND")
        set(${output} "" PARENT_SCOPE)
        return()
    endif()

    set(_closure)
    foreach(_dependency IN LISTS _allows)
        if(NOT TARGET "${_dependency}")
            message(FATAL_ERROR
                "SSG layer violation: ${target} allows missing ${_dependency}")
        endif()
        list(APPEND _closure "${_dependency}")
        _ssg_layer_closure("${_dependency}" _nested)
        list(APPEND _closure ${_nested})
    endforeach()
    list(REMOVE_DUPLICATES _closure)
    set(${output} "${_closure}" PARENT_SCOPE)
endfunction()

function(_ssg_normalize_link item output)
    set(_item "${item}")
    if(_item MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
        set(_item "${CMAKE_MATCH_1}")
    endif()
    set(${output} "${_item}" PARENT_SCOPE)
endfunction()

function(_ssg_normalize_path item output)
    set(_item "${item}")
    if(_item MATCHES "^\\$<BUILD_INTERFACE:([^>]+)>$")
        set(_item "${CMAKE_MATCH_1}")
    endif()
    if(_item MATCHES "^\\$<INSTALL_INTERFACE:")
        set(${output} "" PARENT_SCOPE)
        return()
    endif()
    get_filename_component(_item "${_item}" ABSOLUTE)
    set(${output} "${_item}" PARENT_SCOPE)
endfunction()

function(ssg_assert_layer_graph)
    get_property(_targets GLOBAL PROPERTY SSG_LAYER_TARGETS)
    if(NOT _targets)
        message(FATAL_ERROR "SSG layer violation: no layers declared")
    endif()
    list(REMOVE_DUPLICATES _targets)

    set(_ownedHeaders)
    foreach(_target IN LISTS _targets)
        _ssg_layer_closure("${_target}" _closure)

        get_target_property(_allows "${_target}" SSG_LAYER_ALLOWS)
        if(NOT _allows OR _allows STREQUAL "_allows-NOTFOUND")
            set(_allows)
        endif()
        foreach(_property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
            get_target_property(_links "${_target}" "${_property}")
            if(NOT _links OR _links STREQUAL "_links-NOTFOUND")
                continue()
            endif()
            foreach(_link IN LISTS _links)
                _ssg_normalize_link("${_link}" _link)
                if(NOT TARGET "${_link}")
                    continue()
                endif()
                get_target_property(_declared "${_link}" SSG_LAYER_DECLARED)
                if(_declared AND NOT _link IN_LIST _allows)
                    message(FATAL_ERROR
                        "SSG layer violation: ${_target} links forbidden ${_link}")
                endif()
            endforeach()
        endforeach()

        get_target_property(_root "${_target}" SSG_LAYER_ROOT)
        get_target_property(_privateRoots "${_target}" SSG_LAYER_PRIVATE_ROOTS)
        set(_visibleRoots "${_root}" ${_privateRoots})
        foreach(_dependency IN LISTS _closure)
            get_target_property(_dependencyRoot "${_dependency}" SSG_LAYER_ROOT)
            list(APPEND _visibleRoots "${_dependencyRoot}")
        endforeach()
        list(REMOVE_DUPLICATES _visibleRoots)

        foreach(_property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES)
            get_target_property(_includes "${_target}" "${_property}")
            if(NOT _includes OR _includes STREQUAL "_includes-NOTFOUND")
                continue()
            endif()
            foreach(_include IN LISTS _includes)
                _ssg_normalize_path("${_include}" _include)
                if(NOT _include)
                    continue()
                endif()
                if(NOT _include IN_LIST _visibleRoots)
                    message(FATAL_ERROR
                        "SSG layer violation: ${_target} sees forbidden root ${_include}")
                endif()
            endforeach()
        endforeach()

        get_target_property(_headers "${_target}" SSG_LAYER_HEADERS)
        if(_headers AND NOT _headers STREQUAL "_headers-NOTFOUND")
            foreach(_header IN LISTS _headers)
                if(_header IN_LIST _ownedHeaders)
                    message(FATAL_ERROR
                        "SSG layer violation: duplicate public header ${_header}")
                endif()
                list(APPEND _ownedHeaders "${_header}")
                if(NOT EXISTS "${_root}/ssg/${_header}")
                    message(FATAL_ERROR
                        "SSG layer violation: missing public header ${_header}")
                endif()
            endforeach()
        endif()
    endforeach()
endfunction()
