export const lifecycle = Object.freeze({
  CURRENT: 'current',
  COMPATIBILITY: 'compatibility',
  RETIRED: 'retired',
});

export const replayPolicy = Object.freeze({
  REPLACEMENT: 'replacement',
  CHANGED_REPLACEMENT: 'changed-replacement',
  SPECIALIZED: 'specialized',
  COMPATIBILITY: 'compatibility',
});

export const messageKinds = Object.freeze([
  { symbol: 'CommandRequest', wireName: 'command_request', ordinal: 0,
    lifecycle: lifecycle.CURRENT },
  { symbol: 'SessionSnapshot', wireName: 'session_snapshot', ordinal: 1,
    lifecycle: lifecycle.CURRENT },
  { symbol: 'SessionDelta', wireName: 'session_delta', ordinal: 2,
    lifecycle: lifecycle.CURRENT },
  { symbol: 'ClipboardRequest', wireName: 'clipboard_request', ordinal: 3,
    lifecycle: lifecycle.RETIRED },
  { symbol: 'ClipboardResponse', wireName: 'clipboard_response', ordinal: 4,
    lifecycle: lifecycle.RETIRED },
  { symbol: 'StatusActionInvocation', wireName: 'status_action_invocation',
    ordinal: 5, lifecycle: lifecycle.RETIRED },
  { symbol: 'CommandResult', wireName: 'command_result', ordinal: 6,
    lifecycle: lifecycle.CURRENT },
  { symbol: 'ClientInput', wireName: 'client_input', ordinal: 7,
    lifecycle: lifecycle.CURRENT },
  { symbol: 'ClientInputResult', wireName: 'client_input_result', ordinal: 8,
    lifecycle: lifecycle.CURRENT },
]);

export const semanticSections = Object.freeze([
  { symbol: 'Document', snapshot: 'document',
    delta: ['document', 'document_caret'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.SPECIALIZED },
  { symbol: 'Selection', snapshot: 'selection', delta: ['selection'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'History', snapshot: 'history', delta: ['history'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'Clipboard', snapshot: 'clipboard', delta: ['clipboard'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'PromptStatus', snapshot: 'prompt_status',
    delta: ['prompt_status'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'Search', snapshot: 'search', delta: ['search'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'FindReplace', snapshot: 'find_replace', delta: ['find_replace'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'Settings', snapshot: 'settings', delta: ['settings'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'Keymap', snapshot: 'keymap', delta: ['keymap'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'TextEncoding', snapshot: 'text_encoding',
    delta: ['text_encoding'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.SPECIALIZED },
  { symbol: 'Tabs', snapshot: 'tabs', delta: ['tabs'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'Diff', snapshot: 'diff', delta: ['diff'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'ExternalModification', snapshot: 'external_modification',
    delta: ['external_modification'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.SPECIALIZED },
  { symbol: 'FollowEdits', snapshot: 'follow_edits', delta: ['follow_edits'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'Tree', snapshot: 'tree', delta: ['tree'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'Syntax', snapshot: 'syntax', delta: ['syntax'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'LspSync', snapshot: 'lsp_sync', delta: ['lsp_sync'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'LspFeatures', snapshot: 'lsp_features',
    delta: ['lsp_features'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.SPECIALIZED },
  { symbol: 'Theme', snapshot: 'theme', delta: ['theme'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.REPLACEMENT },
  { symbol: 'Focus', snapshot: 'focus', delta: ['focus'],
    lifecycle: lifecycle.COMPATIBILITY, replay: replayPolicy.COMPATIBILITY },
  { symbol: 'Palette', snapshot: 'palette', delta: ['palette'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.REPLACEMENT },
  { symbol: 'UiFrame', snapshot: 'ui_frame', delta: ['ui_frame_delta'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.SPECIALIZED },
  { symbol: 'PromptView', snapshot: 'prompt_view', delta: ['prompt_view'],
    lifecycle: lifecycle.COMPATIBILITY, replay: replayPolicy.COMPATIBILITY },
  { symbol: 'NoticeView', snapshot: 'notice_view', delta: ['notice_view'],
    lifecycle: lifecycle.CURRENT, replay: replayPolicy.CHANGED_REPLACEMENT },
  { symbol: 'WatcherAvailable', snapshot: 'watcher_available',
    delta: ['watcher_available'], lifecycle: lifecycle.CURRENT,
    replay: replayPolicy.REPLACEMENT },
  { symbol: 'ExternalFocusHeld', snapshot: 'external_focus_held',
    delta: ['external_focus_held'], lifecycle: lifecycle.COMPATIBILITY,
    replay: replayPolicy.COMPATIBILITY },
]);

export default Object.freeze({
  lifecycle,
  replayPolicy,
  messageKinds,
  semanticSections,
});
